version: 1.0.{build}

assembly_info:
  patch: true
  file: **\AssemblyInfo.*
  assembly_version: {version}
  assembly_file_version: {version}
  assembly_informational_version: {version}

configuration: Release

artifacts:
  - path: MarkdownLog/bin/Release/MarkdownLog.dll
    name: MarkdownLog.dll